name: Build and Publish to ghcr.io

on: [ workflow_dispatch ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest 5.34.0 5.30.1 5.28.2 5.26.3 5.24.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BASE_TAG=${{ matrix.version }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}
      
      - name: Build and push (E2E)
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: BASE_TAG=${{ matrix.version }}
          file: Dockerfile.e2e
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}-e2e
