name: Build and Publish to ghcr.io

on: [ workflow_dispatch ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, 5.34.0, 5.30.1, 5.28.2, 5.26.3, 5.24.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}-
            refs/head/main
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BASE_TAG=${{ matrix.version }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push (E2E)
        if: matrix.version == '5.30.1'
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BASE_TAG=${{ matrix.version }}
          file: Dockerfile.e2e
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}-e2e
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push (M8)
        if: matrix.version == '5.30.1'
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BASE_TAG=${{ matrix.version }}
          file: Dockerfile.m8
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}-m8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Build and push (M8-e2e)
        if: matrix.version == '5.30.1'
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: BASE_TAG=${{ matrix.version }}
          file: Dockerfile.m8-e2e
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-perl-cpm/perl-cpm:${{ matrix.version }}-m8-e2e
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
